apiVersion: v1
kind: Service
metadata:
  name: itmo-postgres-service
  namespace: itmo-dev-01
spec:
  selector:
    app: itmo-postgres
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5432
