name: CI/CD counter

on:
  push:
    branches: [ "main" ]

jobs:
  itmo-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'not_empty'
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Login to server
        run: ssh -T root@${{ secrets.SSH_HOST }} exit
      - name: Build Docker image
        run: docker compose build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Counter Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/itmo-counter;
      - name: Push Postgres Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/itmo-postgres;
      - name: Deploy to server
        run: >
          ssh -T root@${{ secrets.SSH_HOST }} "
          docker ps -aq | xargs docker stop | xargs docker rm;
          docker stop $(docker ps -a -q);
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/itmo-counter;
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/itmo-postgres;
          docker run -d -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -p 5432:5432 ${{ secrets.DOCKERHUB_USERNAME }}/itmo-postgres;
          docker run -d -e ITMO_TASK_DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@0.0.0.0:${{ secrets.POSTGRES_PORT }}/counter_info -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/itmo-counter;
          exit
          "
